apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: foobar
    newName: gcr.io/beecash-prod/app/foobar-api
    newTag: master-9705952
generators:
  - scaling.yaml
  - job.yaml
