apiVersion: lummoKRM/v1
kind: LummoRollout
metadata:
  name: test-app
  namespace: test
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/beecash-prod/infra/krm-functions/workloads:latest
spec:
  part-of: foobar
  app: foobar-api
  containers:
    - name: foobar-api
      image: foobar
      command: ["python", "server.py"]
      secrets:
        - foobar-api-database-secrets
      configs:
        - foobar-api-config
  strategy:
    # TODO: work on defining the stages
    # env: prod # prod/pre-prod
    # metrics: error-rate
    # request-type: graphql
    # threshold: "300"
    # TODO: commit templates to workloads/analysis_templates
    - operation: graphql.execute
      errorRPM: "0.1"
      p95latency: "500ms"