apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/instance: api-auxano
    part-of: tokko-api
    product: tokko
  name: tokko-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokko-api
  strategy:
    canary:
      analysis:
        args:
        - name: service-name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: env
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['app.tokko.io/env']
        - name: version
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['app.tokko.io/version']
        startingStep: 2
        templates:
        - templateName: analysis-datadog-tokko-api-graphql-error-rate
      steps:
      - setWeight: 50
      - setWeight: 100
  template:
    metadata:
      annotations:
        app.tokko.io/env: auxano
        app.tokko.io/version: auxano-new-customer-coupon-cijob-2554-commit-54268f2
      labels:
        app: tokko-api
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: APP_TYPE
          value: api
        - name: ENABLE_APM_TRACING
          value: "true"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['app.tokko.io/version']
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['app.tokko.io/env']
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        envFrom:
        - configMapRef:
            name: tokko-api
        - secretRef:
            name: tokko-api
        image: gcr.io/beecash-prod/tokko-api:auxano-new-customer-coupon-cijob-2554-commit-54268f2
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "60"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        name: tokko-api
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          limits:
            cpu: 1
            memory: 2048Mi
          requests:
            cpu: 512m
            memory: 1024Mi
        volumeMounts:
        - mountPath: /app/creds/play-console.json
          name: tokko-api-play-console-volume-external
          readOnly: true
          subPath: play-console.json
      serviceAccountName: tokko-api
      terminationGracePeriodSeconds: 70
      volumes:
      - name: tokko-api-play-console-volume-external
        secret:
          items:
          - key: PLAY_CONSOLE_BILLING_SERVICE_ACCOUNT
            path: play-console.json
          secretName: tokko-api