apiVersion: krm/v1
kind: PubsubTopic
metadata:
  name: pubsub
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/beecash-prod/infra/krm-functions/pubsub:latest
spec:
  prefix: dev-
  topics:
  - topic-a
---
apiVersion: krm/v1
kind: PubsubSubscription
metadata:
  name: pubsub
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/beecash-prod/infra/krm-functions/pubsub:latest
spec:
  prefix: dev-
  subscriptions:
  - topic: topic-a
    subscription: sub-a
    config:
      ttl: "5s"
  - topic: topic-b
    subscription: sub-b
