apiVersion: LummoKRM
kind: LummoDeployment
metadata:
  name: lummo-app
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/beecash-prod/infra/krm-functions/rollouts:latest
spec:
  part-of: foobar
  app: foobar-api
  containers:
    - name: foobar-api
      image: foobar
      command: ["python", "server.py"]
      grpc:
        port: 3000
      http:
        port: 2000
      secrets:
        - foobar-api-database-secrets
        - foobar-api-payment-api-creds
      configs:
        - foobar-api-config
  scaling: 
    minreplica: 1
    maxreplica: 10
    cpu:
      target: "60"
    memory:
      target: "80"
    pubsubTopic:
      name:  dev-tokko-subscription.catalog-integration-product-added
      size: "500"