apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysis-datadog-request-errors
spec:
  args:
  - name: service-name
  - name: env
  - name: version
  - name: errorRPM
  - name: operation
  metrics:
  - failureLimit: 3
    interval: 3m
    name: error-rate
    provider:
      datadog:
        interval: 5m
        query: |
          per_minute(sum:trace.{{args.operation}}.errors{service:{{args.service-name}},env:{{args.env}},version:{{args.version}}}.as_count())
    successCondition: default(result,0) <= {{args.errorRPM}}