name: Build Release Jobs KRM
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build and publish
    uses: bukukasio/krm-functions/.github/workflows/common-build.yaml@master
    inputs:
      function: "jobs"
