name: Build Release Jobs KRM
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build and publish
    uses: bukukasio/krm-functions/.github/workflows/common-build.yaml@master
    with:
      function: "jobs"
    secrets:
      service_account_key: ${{ secrets.GOOGLE_CLOUD_ACCOUNT }}
      project_id: ${{ secrets.BEECASH_PROJECT_ID }}
