name: Build Release Networking KRM
on:
  push:
    branches:
      - test-docker-builds
    paths:
      - 'cmd/networking/**'
      - 'pkg/networking/**'
      - 'pkg/common/**'

jobs:
  build:
    name: build and publish
    uses: bukukasio/krm-functions/.github/workflows/common-build.yaml@master
    with:
      function: "networking"
    secrets:
      service_account_key: ${{ secrets.GOOGLE_CLOUD_ACCOUNT }}
      project_id: ${{ secrets.BEECASH_PROJECT_ID }}
      git_token: ${{ secrets.GH_COMMON_USER_TOKEN }}
