name: Build Release PGbouncer KRM
on:
  push:
    branches:
      - master
      - build-actions
    paths:
      - './cmd/pgbouncer'
      - './pkg/pgbouncer'
      - './pkg/common'

jobs:
  build:
    name: build and publish
    uses: bukukasio/krm-functions/.github/workflows/common-build.yaml@build-actions
    with:
      function: "pgbouncer"
    secrets:
      service_account_key: ${{ secrets.GOOGLE_CLOUD_ACCOUNT }}
      project_id: ${{ secrets.BEECASH_PROJECT_ID }}
