name: Build Release Workloads KRM
on:
  push:
    branches:
      - master
    paths:
      - '**/cmd/workloads/**'
      - '**/pkg/workloads/**'
      - '**/pkg/common/**'
      
jobs:
  build:
    name: build and publish
    uses: bukukasio/krm-functions/.github/workflows/common-build.yaml
    with:
      function: "workloads"
    secrets:
      service_account_key: ${{ secrets.GOOGLE_CLOUD_ACCOUNT }}
      project_id: ${{ secrets.BEECASH_PROJECT_ID }}
      git_token: ${{ secrets.GH_COMMON_USER_TOKEN }}
